# Generated by Django 5.2.5 on 2026-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
