# Generated by Django 5.2.5 on 2026-03-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff'), ('admin', 'Administrator')], default='user', max_length=20),
        ),
    ]
