# Generated by Django 5.2.5 on 2026-03-31 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0004_medicinecategory_supplier_medicine_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Movement', 'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch number for this delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='dispensed_to',
            field=models.CharField(blank=True, help_text='Patient name or department for dispensing', max_length=200),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date of this batch', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='prescription_no',
            field=models.CharField(blank=True, help_text='Prescription or reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price per unit for this delivery', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reference_no',
            field=models.CharField(blank=True, help_text='DR number, PO number, or any reference', max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for Stock In movements', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PharmaSys.supplier'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='strength',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Adjustment'), ('return', 'Return'), ('expired', 'Expired Removal'), ('damaged', 'Damaged / Disposal'), ('audit', 'Audit Adjustment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Positive = stock added, Negative = stock removed'),
        ),
    ]
