# Generated by Django 5.2.5 on 2026-03-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0005_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='dispensed_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='prescription_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PharmaSys.supplier'),
        ),
    ]
