# Generated by Django 5.2.5 on 2026-03-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaSys', '0006_alter_stockmovement_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
